###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=usuarios
            - MYSQL_USER=default
            - MYSQL_PASSWORD=secret
        ports:
            - '26004:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8004:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        environment:
            - XDEBUG_CONFIG=client_host=host.docker.internal
            - PHP_IDE_CONFIG=serverName=${XDEBUG_SERVERNAME}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'

        ### phpMyAdmin ###########################################
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8084:80
        environment:
            - PMA_ARBITRARY=1
